print("----------------------------------------------------")
naam = input("|  Naam      : ")
naam = input("|  Adres     : ")
naam = input("|  Postcode  : ")
naam = input("|  Woonplaats: ")
print("----------------------------------------------------")